# Site settings
title: Pedro Ivo Faria do Amaral
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pedro Ivo
user_description: I believe that the vision of any professional who loves his work area is to innovate above all, experimental practice in my area, are one of my goal, the experimental practice essential to innovate, taking this as principle all my points being achieved this working principle and derives mainly from life.
user_title: Senior Developer and Mathematician
email: pedroivodev@gmail.com
twitter_username: getderived
github_username:  getderived
gplus_username:   getderived

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
